### PR TITLE
(WIP) ClimateChangeAI new interface

### PR DESCRIPTION
**Pull request by notoraptor**

### CODE REVIEW

**Comment by marpaia** [comment]
This interface is looking pretty slick! What do you think about adding React Router or something so that when you select "Contact" or "How it works", the URL changes?

**Comment by notoraptor** [comment]
Hi, @marpaia ! I intentionally discard using React Router because URLs won't be directly available from browser addresse bar. Using React Router, when you access the site through `index.html` entry point, then router URLs will work (e.g. `localhost/contact`), but if you directly put the URL in browser address bar and try to access it, you will get a 404 error page. This is because the site is a pure static web site with only `index.html` file + some CSS and JS files around, so router URLs can only be handled by JS code when loading `index.html`, they cannot work if typed directly.

We initially used React Router on ClimatePixWeb (and here too) and we got this issue, so we ultimately decide to get rid of it on both sites.

**Comment by marpaia** [comment]
I could perhaps add a wildcard URL handler in the Google App Engine configuration to handle this case in production. I think Netlify would handle this case as well. For local development, there might not be as clean of a solution though. What do you think?

**Comment by notoraptor** [comment]
Hi @marpaia ! I don't yet know how URLs would be handled by Google (as I guess it should be handled by static deployed JS code?), but if you have an idea, you can test it and we'll see how it works !

**Pull request merged**
